---
channels:
  - 'conda-forge'
  - 'defaults'
dependencies:
  - 'python==3.13'
  - 'pip'
  - 'matplotlib'
  - 'pandas'
  - pip:
      - 'flepimop2'
      - 'flepimop2-op-engine'
      - 'flepimop2-op-system'
