---
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.13
    - pip
    - pip:
          - flepimop2
          - flepimop2-op-system
          - flepimop2-op-engine
          - matplotlib
          - pandas
